# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build before
      run: dotnet build --no-restore .\before\CentralPackageManagementDemo.Before.sln
    - name: Build after
      run: dotnet build --no-restore .\after\CentralPackageManagementDemo.After.sln
    - name: Test before
      run: dotnet test --no-build --verbosity normal .\before\CentralPackageManagementDemo.Before.sln
    - name: Test after
      run: dotnet test --no-build --verbosity normal .\after\CentralPackageManagementDemo.After.sln
